### PR TITLE
network/default: exclude `wireguard` type

### PR DESCRIPTION
**Pull request by tormath1**
Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>

### CODE REVIEW

**Comment by dongsupark** [comment]
I am not completely sure if this change works well for all cases.
So I would say, let's try to run CI tests for all cloud providers.

**Comment by dongsupark** [comment]
Also when looking into the previous PR https://github.com/flatcar-linux/init/pull/30, should we probably fix other places like `yy-pxe.network` and `yy-vmware.network`?

**Comment by tormath1** [comment]
locally tested with:
```yml
---
variant: flatcar
version: 1.0.0
storage:
  files:
    - path: /etc/systemd/network/zz-default.network.d/wg.conf
      contents:
        inline: |
          [Match]
          Type=!wireguard
    - path: /etc/wireguard/kv0.conf
      contents:
        inline: |
          [Interface]
          Address = ...
          PrivateKey = ...

          [Peer]
          PublicKey = ...
          AllowedIPs = ...
          Endpoint = ...
          PersistentKeepalive = 15
systemd:
  units:
    - name: wg-quick@kv0.service
      enabled: true
```

**Review by dongsupark — APPROVED** [review]

**Comment by tormath1** [comment]
cherr-picked to:
* flatcar-3227-backport

**Pull request merged**
